name = "zinc"
version = "0.1.0"
defaultTargets = ["Zinc", "Jvm"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.34.1"

[[lean_lib]]
name = "Zinc"

[[lean_exe]]
name = "exhaustive"
root = "Exhaustive"

[[lean_exe]]
name = "conformance"
root = "Conformance"

[[lean_exe]]
name = "jconformance"
root = "JConformance"

[[lean_lib]]
name = "Jvm"

[[lean_exe]]
name = "jvmcases"
root = "JvmCases"
